apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-core
  namespace: novapay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-core
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: payments-core
        image: novapay/payments-core:v1.2.0
        ports:
        - containerPort: 8080
        env:
        - name: IDEMPOTENCY_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: novapay-secrets
              key: redis-url
        resources:
          requests:
            memory: "3Gi"
            cpu: "1.5"
          limits:
            memory: "6Gi"
            cpu: "3"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
